export const projects = [
  {
    title: 'Institutional Website.',
    link: 'https://www.bancobari.com.br/',
    resume:
      'Main website Bank Bari, main proposal is generate leads for loans and leads for digital account.',
    images: [
      'assets/projects/website/home.png',
      'assets/projects/website/loan.png',
      'assets/projects/website/faq.png',
    ],
    techs: [
      'Javascript',
      'Next.js',
      'React',
      'Styled Components',
      'Context API',
      'Storybook',
      'TypeScript',
      'Html',
      'CSS',
      'User Experience',
      'Git',
      'Git Lab',
      'Git Flow',
      'JSON',
      'RestFul',
      'Strapi CMS',
      'Agile methodologies experience',
    ],
  },
  {
    title: 'Partners Portal.',
    link: 'https://portal.parceirosbari.com.br/',
    resume: 'An application to manage loans at Bank Bari.',
    text: 'Portal de parceiros is a portal to partners of Bank Bari manage loans. Here the partners can start a simulation, register all proponents, digitl sign (with e-mail and sms) and send all documents. After send the proposal he can follow credit analysis, decline or conclude the loan.',
    images: [
      'assets/projects/portal_partners/list_proposal.png',
      'assets/projects/portal_partners/proposal.png',
      'assets/projects/portal_partners/proponent.png',
    ],
    techs: [
      'Javascript',
      'Next.js',
      'React',
      'Styled Components',
      'Context API',
      'Redux',
      'Storybook',
      'TypeScript',
      'Html',
      'CSS',
      'User Experience',
      'Git',
      'Git Lab',
      'Git Flow',
      'JSON',
      'RestFul',
      'Agile methodologies experience',
    ],
  },
  {
    title: 'LP partners, Digital Sign and Newsletter.',
    link: 'https://www.bancobari.com.br/',
    resume:
      "Project LP's at Bank Bari, this project we provide all LP's for Bank Bari.",
    images: [
      'assets/projects/lp_partners/newsletter.png',
      'assets/projects/lp_partners/by_partners.png',
      'assets/projects/lp_partners/sign.png',
    ],
    techs: [
      'Javascript',
      'React',
      'Styled Components',
      'Context API',
      'Storybook',
      'TypeScript',
      'Html',
      'CSS',
      'User Experience',
      'Git',
      'Git Lab',
      'Git Flow',
      'JSON',
      'RestFul',
      'Agile methodologies experience',
    ],
  },
];
