export const skills = [
  'Software Engineer',
  'Software architecture',
  'Javascript',
  'Next.js',
  'React',
  'React Native',
  'Styled Components',
  'Context API',
  'Redux',
  'Storybook',
  'TypeScript',
  'Node',
  'Html',
  'CSS',
  'User Experience',
  'Git',
  'Git Lab',
  'Git Flow',
  'JSON',
  'JQuery',
  'RestFul',
  'GraphQL',
  'Java',
  'JSF',
  'Spring Boot',
  'Hibernate',
  'JPA',
  'Primefaces',
  'Mongodb',
  'Oracle',
  'Mysql',
  'PostgreSQL',
  'Genexus',
  'Agile methodologies experience',
];
